
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author student
 */
public class Manager extends javax.swing.JFrame {

    /**
     * Creates new form Manager
     */
    public Manager() {
     try {
         initComponents();
         setTable();
         try {
             Class.forName("com.mysql.jdbc.Driver").newInstance();
             Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/SAS","root","");
             
             
             PreparedStatement stmt = con.prepareStatement("select SUM(Quantity) from Employee");
             // stmt.setString(1,id);
             ResultSet rs= stmt.executeQuery();
             while(rs.next())
             {
                 System.out.println(rs.getInt(1));
                 itr.setText(Integer.toString(rs.getInt(1)));
             }
             
                  stmt = con.prepareStatement("select SUM(nofitems) from trans");
           // stmt.setString(1,id);
            rs= stmt.executeQuery();
            while(rs.next())
            {
              System.out.println(rs.getInt(1));
              m1.setText(Integer.toString(rs.getInt(1)));
            }
            
            stmt = con.prepareStatement("select SUM(total) from trans");
           // stmt.setString(1,id);
            rs= stmt.executeQuery();
            while(rs.next())
            {
              System.out.println(rs.getInt(1));
              m3.setText(Integer.toString(rs.getInt(1)));
            }
             
             
         } catch (Exception ex) {
             Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
         }
         
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        }
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        m2 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        m1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        itr = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        m3 = new javax.swing.JLabel();
        statupdate = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        emplist = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        log = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("Manager");

        m2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setText("No of items sold :");

        m1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        m1.setText("00");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel4.setText("Items remaining :");

        itr.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        itr.setText("000");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel6.setText("Counter balance :");

        m3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        m3.setText("00");

        statupdate.setText("Update");
        statupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statupdateActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        jLabel9.setText("Statisitics");

        javax.swing.GroupLayout m2Layout = new javax.swing.GroupLayout(m2);
        m2.setLayout(m2Layout);
        m2Layout.setHorizontalGroup(
            m2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(m2Layout.createSequentialGroup()
                .addGroup(m2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(m2Layout.createSequentialGroup()
                        .addGroup(m2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(m2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel2))
                            .addGroup(m2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(m2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4))))
                        .addGap(32, 32, 32)
                        .addGroup(m2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itr)
                            .addComponent(m1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m3)))
                    .addGroup(m2Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, m2Layout.createSequentialGroup()
                        .addComponent(statupdate)
                        .addGap(61, 61, 61)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        m2Layout.setVerticalGroup(
            m2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(m2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(41, 41, 41)
                .addGroup(m2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(m2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itr, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(m2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(m3))
                .addGap(28, 28, 28)
                .addComponent(statupdate)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        m2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        m2.setLayer(m1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        m2.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        m2.setLayer(itr, javax.swing.JLayeredPane.DEFAULT_LAYER);
        m2.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        m2.setLayer(m3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        m2.setLayer(statupdate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        m2.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        emplist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(emplist);
        if (emplist.getColumnModel().getColumnCount() > 0) {
            emplist.getColumnModel().getColumn(0).setResizable(false);
            emplist.getColumnModel().getColumn(1).setResizable(false);
            emplist.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel8.setText("List");

        log.setText("Logout");
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(415, 415, 415)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(log)
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(m2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(log))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(m2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void statupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statupdateActionPerformed

     
     try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/SAS","root","");
            
            
            PreparedStatement stmt = con.prepareStatement("select SUM(Quantity) from Employee");
           // stmt.setString(1,id);
            ResultSet rs= stmt.executeQuery();
            while(rs.next())
            {
              System.out.println(rs.getInt(1));
              itr.setText(Integer.toString(rs.getInt(1)));
            }
            
            stmt = con.prepareStatement("select SUM(nofitems) from trans");
           // stmt.setString(1,id);
            rs= stmt.executeQuery();
            while(rs.next())
            {
              System.out.println(rs.getInt(1));
              m1.setText(Integer.toString(rs.getInt(1)));
            }
            
            stmt = con.prepareStatement("select SUM(total) from trans");
           // stmt.setString(1,id);
            rs= stmt.executeQuery();
            while(rs.next())
            {
              System.out.println(rs.getInt(1));
              m3.setText(Integer.toString(rs.getInt(1)));
            }
           
            
        } catch (Exception ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        }
     
 }
    
    
    
    private void setTable() throws SQLException 
    {
        //System.out.println("settanle");
        DefaultTableModel model = (DefaultTableModel) emplist.getModel();
        emplist.setModel(model);
        try{
        Class.forName("com.mysql.jdbc.Driver").newInstance();
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/SAS","root","");
        Statement stmt=con.createStatement();
        ResultSet rs=stmt.executeQuery("select * from Login ");
       // model.addRow(new Object[]{"", "", "", "", "", "" });
       while (rs.next()) 
       {
            String id = rs.getString("ID");
            String name = rs.getString("UserName");
            String mrp = rs.getString("type");
            
            model.addRow(new Object[]{id, name, mrp });
        }
        } catch (Exception ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

 public boolean login_enquiry(String username, String Password,String type) {

        try {
               Class.forName("com.mysql.jdbc.Driver").newInstance();
               Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/SAS","root","");
            String OrgUser = "";
            String OrgPass = "";

            PreparedStatement stmt = con.prepareStatement("select * from Login where UserName=? and Password=? and type=? ");
            stmt.setString(1, username);
            stmt.setString(2, Password);
            stmt.setString(3,type);
            ResultSet rs = stmt.executeQuery();
            
            if (rs.next()) {
               
                System.out.println(rs.getString("UserName"));

                return true;
            } else {
                return false;
            }

        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        } catch (InstantiationException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        }// TODO add your handling code here:
        return false;
    }//GEN-LAST:event_statupdateActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed

        if(evt.getSource() == log)
        {
            setVisible(false);
            new Home().setVisible(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_logActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable emplist;
    private javax.swing.JLabel itr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton log;
    private javax.swing.JLabel m1;
    private javax.swing.JLayeredPane m2;
    private javax.swing.JLabel m3;
    private javax.swing.JButton statupdate;
    // End of variables declaration//GEN-END:variables
}
